// Code generated by MockGen. DO NOT EDIT.
// Source: psp.go

// Package mock_psp is a generated GoMock package.
package mock_psp

import (
	psp "banking-system/psp"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockPaymentServiceProvider is a mock of PaymentServiceProvider interface.
type MockPaymentServiceProvider struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentServiceProviderMockRecorder
}

// MockPaymentServiceProviderMockRecorder is the mock recorder for MockPaymentServiceProvider.
type MockPaymentServiceProviderMockRecorder struct {
	mock *MockPaymentServiceProvider
}

// NewMockPaymentServiceProvider creates a new mock instance.
func NewMockPaymentServiceProvider(ctrl *gomock.Controller) *MockPaymentServiceProvider {
	mock := &MockPaymentServiceProvider{ctrl: ctrl}
	mock.recorder = &MockPaymentServiceProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentServiceProvider) EXPECT() *MockPaymentServiceProviderMockRecorder {
	return m.recorder
}

// PayIn mocks base method.
func (m *MockPaymentServiceProvider) PayIn() (*psp.DepositResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PayIn")
	ret0, _ := ret[0].(*psp.DepositResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PayIn indicates an expected call of PayIn.
func (mr *MockPaymentServiceProviderMockRecorder) PayIn() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PayIn", reflect.TypeOf((*MockPaymentServiceProvider)(nil).PayIn))
}
