// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/payments/cancel": {
            "post": {
                "description": "Handles the cancellation callback from the Payment Service Provider (PSP) when a deposit is cancelled.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "payments"
                ],
                "summary": "Cancel a Deposit Transaction",
                "parameters": [
                    {
                        "type": "string",
                        "description": "PSP API Key",
                        "name": "X-PSP-API-Key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Cancellation callback from PSP",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/psp.CancelRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Deposit cancelled successfully",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - Invalid API key",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/payments/confirm": {
            "post": {
                "description": "Handles the confirmation callback from the Payment Service Provider (PSP) after a successful deposit.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "payments"
                ],
                "summary": "Confirm a Deposit Transaction",
                "parameters": [
                    {
                        "type": "string",
                        "description": "PSP API Key",
                        "name": "X-PSP-API-Key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Confirmation callback from PSP",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/psp.PayInResponse"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Deposit confirmed successfully",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - Invalid API key",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/payments/deposit": {
            "post": {
                "description": "Creates a new PENDING transaction and redirects the user to the Payment Service Provider (PSP) for payment completion.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "payments"
                ],
                "summary": "Initiate a Deposit Transaction",
                "parameters": [
                    {
                        "description": "Deposit initiation details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.DepositRequest"
                        }
                    }
                ],
                "responses": {
                    "302": {
                        "description": "Redirect to PSP payment page",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/payments/transfer": {
            "post": {
                "description": "Transfers funds from one user's wallet to another user's wallet atomically.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "payments"
                ],
                "summary": "Transfer Funds Between Users",
                "parameters": [
                    {
                        "description": "Transfer details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.TransferRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Transfer completed successfully"
                    },
                    "400": {
                        "description": "Bad request - validation error or insufficient balance",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/payments/withdraw": {
            "post": {
                "description": "Creates a new PENDING withdrawal transaction, deducts the amount from wallet balance, and sends request to PSP for processing.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "payments"
                ],
                "summary": "Initiate a Withdrawal Transaction",
                "parameters": [
                    {
                        "description": "Withdrawal initiation details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.WithdrawRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Withdrawal initiated successfully"
                    },
                    "400": {
                        "description": "Bad request - validation error or insufficient balance",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.DepositRequest": {
            "type": "object",
            "required": [
                "amount",
                "currency",
                "user_id"
            ],
            "properties": {
                "amount": {
                    "type": "number"
                },
                "currency": {
                    "type": "string"
                },
                "payment_method": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "models.TransferRequest": {
            "type": "object",
            "required": [
                "amount",
                "currency",
                "recipient_user_id",
                "sender_user_id"
            ],
            "properties": {
                "amount": {
                    "type": "number"
                },
                "currency": {
                    "type": "string"
                },
                "recipient_user_id": {
                    "type": "integer"
                },
                "sender_user_id": {
                    "type": "integer"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "models.WithdrawRequest": {
            "type": "object",
            "required": [
                "amount",
                "currency",
                "user_id"
            ],
            "properties": {
                "amount": {
                    "type": "number"
                },
                "currency": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "psp.CancelRequest": {
            "type": "object",
            "properties": {
                "transactionID": {
                    "type": "string"
                }
            }
        },
        "psp.PayInResponse": {
            "type": "object",
            "properties": {
                "redirectUrl": {
                    "type": "string"
                },
                "transactionID": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
