// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/bank-account": {
            "get": {
                "description": "Retrieves all bank accounts for the authenticated user",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "bank-accounts"
                ],
                "summary": "Get all bank accounts",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Bank accounts retrieved successfully",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.BankAccountResponse"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a new bank account for the authenticated user",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "bank-accounts"
                ],
                "summary": "Create a new bank account",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Bank account creation details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreateBankAccountRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Bank account created successfully",
                        "schema": {
                            "$ref": "#/definitions/models.BankAccountResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request - validation error",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/bank-account/user/{userId}": {
            "get": {
                "description": "Retrieves all bank accounts for a specific user by user ID",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "bank-accounts"
                ],
                "summary": "Get all bank accounts by user ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Bank accounts retrieved successfully",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.BankAccountResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/bank-account/{id}": {
            "get": {
                "description": "Retrieves a specific bank account by ID for the authenticated user",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "bank-accounts"
                ],
                "summary": "Get a bank account by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Bank Account ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Bank account retrieved successfully",
                        "schema": {
                            "$ref": "#/definitions/models.BankAccountResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "404": {
                        "description": "Bank account not found",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            },
            "put": {
                "description": "Updates a specific bank account by ID for the authenticated user",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "bank-accounts"
                ],
                "summary": "Update a bank account",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Bank Account ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Bank account update details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UpdateBankAccountRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Bank account updated successfully",
                        "schema": {
                            "$ref": "#/definitions/models.BankAccountResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "404": {
                        "description": "Bank account not found",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes a specific bank account by ID for the authenticated user",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "bank-accounts"
                ],
                "summary": "Delete a bank account",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Bank Account ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Bank account deleted successfully"
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "404": {
                        "description": "Bank account not found",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/payments/cancel": {
            "post": {
                "description": "Handles the cancellation callback from the Payment Service Provider (PSP) when a deposit is cancelled.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "payments"
                ],
                "summary": "Cancel a Deposit Transaction",
                "parameters": [
                    {
                        "type": "string",
                        "description": "PSP API Key",
                        "name": "X-PSP-API-Key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Cancellation callback from PSP",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/psp.CancelRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Deposit cancelled successfully",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - Invalid API key",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/payments/confirm": {
            "post": {
                "description": "Handles the confirmation callback from the Payment Service Provider (PSP) after a successful deposit.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "payments"
                ],
                "summary": "Confirm a Deposit Transaction",
                "parameters": [
                    {
                        "type": "string",
                        "description": "PSP API Key",
                        "name": "X-PSP-API-Key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Confirmation callback from PSP",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/psp.PayInResponse"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Deposit confirmed successfully",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - Invalid API key",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/payments/deposit": {
            "post": {
                "description": "Creates a new PENDING transaction and returns the redirect URL to the Payment Service Provider (PSP) for payment completion.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "payments"
                ],
                "summary": "Initiate a Deposit Transaction",
                "parameters": [
                    {
                        "description": "Deposit initiation details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.DepositRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Deposit initiated successfully with PSP redirect URL",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "redirect_url": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request - validation error",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/payments/transfer": {
            "post": {
                "description": "Transfers funds from one user's wallet to another user's wallet atomically.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "payments"
                ],
                "summary": "Transfer Funds Between Users",
                "parameters": [
                    {
                        "description": "Transfer details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.TransferRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Transfer completed successfully"
                    },
                    "400": {
                        "description": "Bad request - validation error or insufficient balance",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/payments/withdraw": {
            "post": {
                "description": "Creates a new PENDING withdrawal transaction, deducts the amount from wallet balance, and sends request to PSP for processing.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "payments"
                ],
                "summary": "Initiate a Withdrawal Transaction",
                "parameters": [
                    {
                        "description": "Withdrawal initiation details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.WithdrawRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Withdrawal initiated successfully"
                    },
                    "400": {
                        "description": "Bad request - validation error or insufficient balance",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/user": {
            "post": {
                "description": "Creates a new user with hashed password and an associated wallet with initial balance of 0",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Register a new user",
                "parameters": [
                    {
                        "description": "User registration details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "User created successfully"
                    },
                    "400": {
                        "description": "Bad request - validation error or user already exists",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/user/login": {
            "post": {
                "description": "Authenticates a user with username and password, and sets an authorization cookie",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "User Login",
                "parameters": [
                    {
                        "description": "Login form data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User logged in successfully"
                    },
                    "400": {
                        "description": "Bad Request (e.g., invalid body or validation error)",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "401": {
                        "description": "Unauthorized (Invalid username or password)",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.BankAccountResponse": {
            "type": "object",
            "properties": {
                "account_number": {
                    "type": "string"
                },
                "bank_code": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "models.CreateBankAccountRequest": {
            "type": "object",
            "required": [
                "account_number",
                "bank_code"
            ],
            "properties": {
                "account_number": {
                    "type": "string",
                    "maxLength": 100
                },
                "bank_code": {
                    "type": "string",
                    "maxLength": 50
                }
            }
        },
        "models.DepositRequest": {
            "type": "object",
            "required": [
                "amount",
                "uuid"
            ],
            "properties": {
                "amount": {
                    "type": "number"
                },
                "payment_method": {
                    "type": "string"
                },
                "userID": {
                    "type": "integer"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "models.LoginRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "models.RegisterRequest": {
            "type": "object",
            "required": [
                "name",
                "password",
                "username"
            ],
            "properties": {
                "name": {
                    "type": "string",
                    "maxLength": 100
                },
                "password": {
                    "type": "string",
                    "maxLength": 20
                },
                "username": {
                    "type": "string",
                    "maxLength": 20
                }
            }
        },
        "models.TransferRequest": {
            "type": "object",
            "required": [
                "amount",
                "recipient_user_id",
                "sender_user_id"
            ],
            "properties": {
                "amount": {
                    "type": "number"
                },
                "recipient_user_id": {
                    "type": "integer"
                },
                "sender_user_id": {
                    "type": "integer"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "models.UpdateBankAccountRequest": {
            "type": "object",
            "required": [
                "account_number",
                "bank_code"
            ],
            "properties": {
                "account_number": {
                    "type": "string",
                    "maxLength": 100
                },
                "bank_code": {
                    "type": "string",
                    "maxLength": 50
                }
            }
        },
        "models.WithdrawRequest": {
            "type": "object",
            "required": [
                "amount"
            ],
            "properties": {
                "amount": {
                    "type": "number"
                },
                "payment_method": {
                    "type": "string"
                },
                "userID": {
                    "type": "integer"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "psp.CancelRequest": {
            "type": "object",
            "required": [
                "transaction_id"
            ],
            "properties": {
                "transaction_id": {
                    "type": "string"
                }
            }
        },
        "psp.PayInResponse": {
            "type": "object",
            "properties": {
                "redirectUrl": {
                    "type": "string"
                },
                "transactionID": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
