// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/payments/confirm": {
            "post": {
                "description": "Handles the confirmation callback from the Payment Service Provider (PSP) after a successful deposit.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "payments"
                ],
                "summary": "Confirm a Deposit Transaction",
                "responses": {
                    "200": {
                        "description": "Deposit confirmed successfully",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/payments/deposit": {
            "post": {
                "description": "Creates a new PENDING transaction and redirects the user to the Payment Service Provider (PSP) for payment completion.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "payments"
                ],
                "summary": "Initiate a Deposit Transaction",
                "parameters": [
                    {
                        "description": "Deposit initiation details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.DepositRequest"
                        }
                    }
                ],
                "responses": {
                    "302": {
                        "description": "Redirect to PSP payment page",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.DepositRequest": {
            "type": "object",
            "required": [
                "amount",
                "currency",
                "user_id"
            ],
            "properties": {
                "amount": {
                    "type": "number"
                },
                "currency": {
                    "type": "string"
                },
                "payment_method": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                },
                "uuid": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
